SeaGL/seagl.github.io

- _config.yml
- _posts/2015-02-20-Dates-Announced.md
I complained to Deb about the 2015 dates not being posted. 
She looked up the email with the dates and we wrote this. 
I think fixing the config is all it takes to change the sidebar? It's the only place where "October 24th" occurred in the old site.
> Add 2015 dates to site

- get_involved.html
Updated page to reflect that 2015 CFP and exhibitor info are forthcoming.
Minor punctuation change on Stay in Touch sidebar.
> Edited get_involved.html

- _posts/2015-06-25-CFP-Open.md
Deb would like to review before the commit is merged.
> Added CFP post

- _posts/2015-07-28-CFP-extended.md
Added post to remind readers about Sunday: the last live IRC help session and the close of the CFP.
> Added CFP closing post

- _posts/2015-07-28-CFP-extended.md
- get_involved.html
- schedule/2015.html
Removed the open CFP info from get_involved.html and added OSEM schedule link to 2015.html.
> Site edits

- index.html
```
21:36:39 < strugee> hey, all
21:36:50 < strugee> OSEM isn't linked to on the seagl.org homepage
21:36:53 < strugee> just FYI
```
> Credit the tools that run SeaGL, in 'about'

- _posts/2015-10-16-QA-garretthoneycutt.md
One more speaker Q&A for the site.
> Added Garrett Honeycutt Q&A

- _config.yml
> 2016 dates

- _posts/2016-05-13-CFP-Open
Line 18: I assume this year's submission URL will be https://osem.seagl.org/conference/seagl2016/proposal. 
I also need the CFP deadline.
> Create post for 2016 CFP

- css/app/seagl.css
> fix #65: hide registration ribbon overflow

- _posts/2016-05-12-2015-videos.md
Added post for 2015 keynote videos.
> 2015 videos

- _posts/2016-06-24-Office-Hours.md
I don't use a lot of GitHub for real pull requests, so feel free to let me know if I'm doing it all wrong! Looks like a lovely conference.
> Fixing a few tiny typos

- _includes/footer.html
- _includes/header.html
- _layouts/flier.html
I can give accounts to whoever needs them.
> Remove Google Analytics, add Piwik.

- _posts/2016-10-08-Call-for-Volunteers.md
Please check for typos, information, etc.
> Add Call for Volunteers post

- README.md
- _posts/2017-06-19-CFP-open.md
I wanted to make this (blog posting in particular) more accessible to less technical contributors, so I revamped README to add a lot of instructions.
* Most instructions assume a less technical reader
* There are some sections ("on your local machine") which could use some verbose content
* Some day (not today), the testing stuff should be enhanced to support less technical readers as well
> Big ol' README update

- _posts/2017-07-27-CascadiaNominationsOpen.md
- _posts/2017-08-19-CA_nomsclosing.md
Closes https://github.com/SeaGL/seagl.github.io/issues/92
> fix typo: Casacadia -> Cascadia

- _posts/2018-04-09-code_of_practice.md
Blog post draft for review by speakers@ & whoever else wants to have a look
> 2018 codeofpractice cfp dates announcement

- _includes/menu.html
- _posts/2018-06-04-CFP-open.md
Draft of CFP announcement/instructions.
_None_ of this is approved by the programme committee yet.
> DO NOT MERGE UNTIL JUNE 4TH

- css/app/ribbon.css
Co-Authored-By: Wm Salt Hale <salt@altsalt.net>
> Extend ribbon so text doesn't wrap

- Dockerfile
- README.md
> fix and simplify containerized dev environment

- _config.yml
- _includes/footer.html
- index.html
> remove Google+

- _includes/menu.html
> Update schedule link to 2019

- _config.yml
- css/app/seagl.css
- maps/2019.html
Re #96, how do you feel about [Mapbox]?
[Mapbox]: https://wiki.openstreetmap.org/wiki/Mapbox
> Use Mapbox instead of Google Maps.

- _posts/2020-06-12-black-lives-matter.md
> BLM statement (continued)

- _posts/2020-08-05-honoraria.md
Co-authored-by: Nathan Handler <nhandler@seagl.org>
> honoraria first draft from rachel & nathan

- _posts/2020-07-14-CFP-open.md
Using top of page comment to note deadline extension per vmbrasseur suggestion.
> Cfp top update

- _posts/vmbrasseur-keynote-interview.md
I am deeeeeeply sorry this has taken longer than I told you it would. It's been really hard for me to write lately. :-(
Anyway, here are the answers to most of the questions y'all posed me.
**This post will need a title and probably one of y'all to add some sort of introduction before merging/publishing.**
I still owe you a separate post for the final "why SeaGL?" question. That's still pending but I hope to get it to you soon.
Please let me know what else I can do to help!
> Add interview blog post

- _posts/2020-09-09-why-seagl.md
Answering the final question of the keynote interview.
> Add a 'Why SeaGL' post

- _posts/2020-08-31-teagl-online.md
blog post from Monica, review and merge as able
> Teagl online

- _posts/2020-09-10-naming-contest.md
Updates the seagull naming contest blog post with the winning name.
> Update seagull naming blog post

- _posts/2020-10-05-call-for-volunteers.md
I wanted to wait until we had a tech stack to post this, but given
that's so late in the game I think it's easier to post this now and try
to fill out the (growing) volunteer spreadsheet.
> (maint) Call for Volunteers blog post

- _posts/2020-11-09-seagl-tech-stack.md
This post is functional but lacks any...heart? I figured I'd throw it open to suggestion from the team, since I can't make any more progress on it myself.
> Add a post about the tech stack

- get_involved.html
Quick update to reflect organization for 2021 has started
> update volunteer page for 2021 organizing

- _config.yml
- _includes/ribbon.html
- _welcome.md
> Publish 2021 conference dates

- _posts/2021-06-08-format-2021.md
> Draft of a post on the decision to go virtual in 2021

- _posts/2021-07-30-office_hours.md
> Add a post for the 2021 office hours

- _welcome.md
This version was written October 21, 2020 and received multiple +1's in the thread titled, "SeaGL mission" started August 3, 2020.
> Updated copy for side bar About section

- _config.yml
- css/app/seagl.scss
- exhibitor_faq.html
- get_involved.html
- index.html
- meet.html
Trying to find the right balance between concise and educational. Feedback appreciated!
> Explanation of Matrix and IRC

- press.html
@funnelfiasco made some small changes to the text, mostly new links. Still need to actually add a JPG file. @AndrewKvalheim could you perhaps do that?
> small updates to press page

- get_involved.html
Updated verbiage to reflect the virtual only nature of the conference.
> Update to Volunteer Section of Get Involved

- _posts/2021-08-24-lightning-talks.md
Move from a Due Date to rolling submission for lightning talks.
> Update Lightning Talks Due Date

- _config.yml
- _includes/footer.html
@altsalt and I discussed this yesterday and we think adding the press kit link to the footer is the best approach, but we're open to other ideas.
> Add the press kit to the footer

- get_involved.html
> update language on get_involved page for sponsors

- _posts/2021-09-27-2021_keynote_announcement.md
It's a little more bare than I'd planned, but it gets the job done. Suggestions welcome!
> First draft of keynote announcement

- _posts/2021-10-29-seagl-2021-career-expo-announcement.md
Fixes up some formatting from #295
> Career expo announce

- matrix-client
- matrix-server
Pending decommissioning of ephemeral homeserver
> Remove .well-known/matrix

- _posts/2022-07-22-office-hours.md
This change adds a new blog post announcing the 2022 CFP Office Hours
> Announce 2022 CFP Office Hours

- _data/sponsors.yml
This fixes:
```
github-pages 227 | Error:  (/github/workspace/_data/sponsors.yml): found a tab character where an indentation space is expected while scanning a block scalar at line 169 column 16
```
> Fix one more sponsors.yml Whitespace Error

- _posts/2022-10-10-keynote-aeva-black.md
Like [this](https://seagl.org/news/2018/05/02/2018_keynoter-elizabeth_krumbach_joseph), but I chose the right side.
> Reduce image size and align to side of post

- attend-ephemeral.md
- attend.md
Lots of stuff wrong here that needs fixing/tweaking (buttons are too small, URLs are terrible, etc.) but I want to get this online quickly so we can get feedback from the whole staff. This seems fine since we're not linking this anywhere yet.
> Onboarding 2022 first draft

- attend.md
- attend/ephemeral.md
- attend/existing.md
And polish a few miscellaneous things (particularly URLs) at the same time.
> Add "existing Matrix account" attend flow

- _includes/jumbotron.html
- index.md
> Add landing section to front page

- attend.md
- attend/ephemeral.md
This contains most of the edits from #365 except https://github.com/SeaGL/seagl.github.io/pull/365/files#diff-6f162e2dfcaa34b07bb560a60b8aabfd9a87caceeb6bcd34bf8e23e8f4542898L31.
> Update ephemeral page

- _archive-sessions/2022/a-brief-introduction-to-the-fediverse.md
- _archive-sessions/2022/accessible-data-visualization.md
- _archive-sessions/2022/building-a-cdn-edge-using-open-source.md
- _archive-sessions/2022/choose-your-candidate.md
- _archive-sessions/2022/cross-pollinate-your-volunteering.md
- _archive-sessions/2022/falling-off-the-platform.md
- _archive-sessions/2022/finding-the-right-tools-for-your-new-job.md
- _archive-sessions/2022/firefox-multi-account-containers.md
- _archive-sessions/2022/free-riders-and-the-motivations-that-keep-oss-developers-writing-code.md
- _archive-sessions/2022/grow-your-foss-project-with-this-one-weird-trick.md
- _archive-sessions/2022/gulls-do-gull.md
- _archive-sessions/2022/intermediate-jq-sed-for-json.md
- _archive-sessions/2022/keynote-sumana-harihareswara.md
- _archive-sessions/2022/on-growth-tips-to-grow-a-healthy-open-source-community.md
- _archive-sessions/2022/open-source-its-outta-this-world.md
- _archive-sessions/2022/programmer-culture-the-odd-phenomenon-of-recreational-programming.md
- _archive-sessions/2022/self-hosting-simple-web-apps-with-traefik-and-docker-compose.md
- _archive-sessions/2022/struggles-and-possible-solutions-of-a-local-free-software-movement.md
- _archive-sessions/2022/tab-completion-for-your-custom-commands.md
- _archive-sessions/2022/ten-years-of-seagl.md
- _archive-sessions/2022/the-cloud-native-burrito.md
- _archive-sessions/2022/the-fediverse-at-your-library.md
- _archive-sessions/2022/the-internet-is-unusable-the-disabled-view.md
- _archive-sessions/2022/the-leaky-pipeline.md
- _archive-sessions/2022/the-small-web.md
- _archive-sessions/2022/the-struggle-of-getting-an-open-source-community-off-the-ground.md
- _archive-sessions/2022/til-2022-floss-research-roundup.md
- _archive-sessions/2022/victims-of-our-success.md
- _archive-sessions/2022/virtual-data-optimizer.md
- _archive-sessions/2022/whats-anonymity-worth.md
Pending upload of processed videos to the Internet Archive
> Link to Internet Archive videos from 2022 archive

- _posts/2023-03-08-CFP-Open.md
Update CfP blog post with new date.
Strikethrough old date and write new deadline.
> Update CfP blog post with new date.

- style_guide.md
The remainder of the broken links I wasn't quite sure what the right destination for them was (and for some of them, seems like they need to be created in the first place).
Ref #318
> Update some style guide broken links

- fliers/2023/index.html
Add fossy flier poster pdf and update index
> Add fossy flier poster pdf

- _posts/2023-10-05-IDEA-Sharing-at-SeaGL.md
- _posts/2023-10-23-IDEA-Sharing-at-SeaGL.md
uncertain on publish date and such, but adding for wider staff review.
> add 2023 IDEA blog post

- _data/schedule.yml
- _includes/jumbotron.html
- archive.html
- css/app/seagl.scss
- index.md
- watch.html
> Add day 1 content

- _config.yml
- _includes/footer.html
I did not test this quite literally at all
> Add link to status page

- health_and_safety_policy.md
mostly reorganization at this point...
> 2024 health and safety changes

- attend/existing.md
I literally did a find and replace and just skimmed the results.
Screenshots are from 2022 still.
> s/2023/2024/ in `/attend/existing`

- _posts/2025-01-01-thank-you-2024-welcome-2025
* Adds thank you to attendees, sponsors, speakers and volunteers for SeaGL 2024.
* Adds save the date for SeaGL 2025.
> Adds blog post thank you for 2024 and save the date for 2025

- _includes/footer.html
- get_involved.md
- index.md
As discussed in today’s cross-committe meeting
> Avoid promoting Twitter

- get_involved.md
Adds Keynote nomination blurb and link within the Get Involved page.
> Add keynote link to get involved
