_includes/footer.html
Because during the last meeting, I searched for 'conduct' on the front page and found nothing. Also the contrast on that footer is pretty poor and might be difficult for those with visual challenges, so making it searchable improves accessibility.
=> name the code of conduct link more clearly

_posts/2015-10-13-QA-aaronwolf.md, get_involved.html
Updated the get_involved.html file to delete the Cascadia award information. I also added information for volunteering.
=> Fixes #37. Removed Cascadia award section and added volunteer info

_config.yml
When building the site the following warning is issued by GitHub:
```
The page build completed successfully, but returned the following warning:
You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
For information on troubleshooting Jekyll see:
https://help.github.com/articles/troubleshooting-jekyll-builds
If you have any questions you can contact us by replying to this email.
```
This patch adds the recommended config to suppress the …
=> explicitly specify highlighter in config to suppress build warning

_includes/menu.html
We don't have a schedule yet, but we *do* have a CFP open right now. It needs more exposure, so I've switched the 'Schedules' link from the header to be 'CFP'. It points to the announcement blog post, as that has the best information for the CFP. I don't like that there's an acronym in the link text, but "Call For Proposals" wrapped & messed up the header layout.
This would also handle issue #88.
=> Change Schedule menu item to CFP

sponsors/2018.html, sponsors/index.html
In header and elsewhere (2018 was missing).
Also add not yet added years to `/sponsors` index.
Notes/possible followup issues:
- 2018 prospectus not online
- Would be possible to change `_layouts/sponsors.html` so that if no current sponsors (like 2018) instead of showing blank levels, link to `/sponsors` thanking past sponsors or something like that.
=> fix sponsors link

index.html
This adds a note that attendees do not have to register to attend SeaGL,
and moves this memo along with the anonymity higher in the About sidebar
as well, for visibility
=> Clarify that registration is not required to attend

_layouts/sponsors.html
While I was testing the security patch this morning I noticed that our sponsor links take the users away from our site vs having a target = blank to open in a new tab. This will keep SeaGL open in the users browsers. :)
=> added blank target for sponsor links

.gitignore, README.md, backstop.json, maps/2019.html
I like to have something like this set up when working on an existing site so I can catch accidental changes.
This commits just the configuration so that it's easy to get started; the heavy lifting is done by an optional dependency.
Also slipping in a few edits to the readme leading up to this.
=> Add configuration for visual regression testing.

_config.yml
freenode brands itself as freenode (with a lowercase `f`). This can be seen on https://freenode.net/project.
=> Replace Freenode with freenode

_includes/footer.html
This adds a note to the footer about how folks who are interested in
helping organize and run SeaGL can reach us and help. We want everyone
who is interested to let us know and also want to ask for specific
skills we're looking for, so I made the call both broad and listed the
roles we need filled. This footer will be included in every SeaGL
website page.
=> Add note about participating to footer

_posts/2020-07-14-CFP-open.md
We etended the CFP. This naturally means that we need to push back the dates we originally said we would notify speakers about talk acceptances.﻿
=> Update CFP update to clarify that speaker notifications will be delayed due to CFP extension

README.md
In order to make it easier for collaboration on blog posts and content,
contributors should enable the repo's maintainers to made edits to the
pull request.
This is (as far as I know) a relatively new feature of GitHub and it means my original plan to suggest using branches on the main repo instead of forks is no longer necessary. Either will work just as well.
=> Add instructions about maintainer edits

_posts/2020-10-05-call-for-volunteers.md
This updates the volunteers blog post to account for the new tech stack
and speaker-flow. Because we won't have participants on video a video
help-desk is no longer necessary. We will also have SeaGL staff managing
the technical side of the videos and IRC channels, so a per-talk IRC
channel isn't necessary. This updates the blog post to remove the
unnecessary positions, and updates descriptions.
=> Update volunteer blog post

_config.yml
Re SeaGL/organization#125. Implementation notes:
- Preserving Freenode links in old blog posts
- Webchat pending https://github.com/Libera-Chat/libera-chat.github.io/issues/19
=> Change chat links from Freenode to Libera.Chat

code_of_practice.html, css/app/code_of_practice.css
This year, we are creating a static Code of Practice page on the site
rather than a blog post. The Code of Practice doesn't really change from
year to year. Instead, we re-affirm our commitment to abide by it. By
having it as a static page, it will be easier to re-use, link to, and
reference.
=> Create Code of Practice Page

_config.yml, _posts/2021-06-24-cfp.md
OSEM currently makes for a terrible landing page. Want to use the CFP announcement post for that instead?
- [main navigation](https://github.com/SeaGL/seagl.github.io/commit/dcc54177a2851f1612be38e18738de73f1556f6a) → announcement
- [seagl.org/cfp](https://seagl.org/) → announcement
- announcement → OSEM
=> Use CFP announcement post as a landing page

_config.yml, chat.html
Re [last meeting](https://github.com/SeaGL/organization/blob/master/meetings/2021/20210712-allhands.md#getting-staff-into-matrix-rooms-salt) and some clarification from @altsalt, I’ve customized Kiwi IRC over at [SeaGL/chat.seagl.org](https://github.com/SeaGL/chat.seagl.org) similar to what we had for the virtual conference, but simpler for the sake of maintainability—no Jitsi integration, no embedded videos, no suggested channels, and none of the UI customizations that required a fork.
Please have a look and let me know what else would be helpful.
=> Customized webchat

_posts/2021-06-24-cfp.md, _posts/2021-08-05-cfp_extended.md
Post for CfP extension discussed via email. Adds a new post and updates the CfP post with the new deadline.
=> Extend the CfP by two weeks

_includes/footer.html, _welcome.md, css/app/seagl.scss
Re @funnelfiasco’s suggestions:
> 1. Add an "Announcements" section to the sidebar that says "Sign up for our low-traffic \[announcement mailing list\](URL goes here) to stay informed."
>
> 2. Adding the same to the footer so it appears on all of the blog posts, etc
Sounds good to me. Here’s something along those lines.
I mentioned the RSS feed as well—
> <img alt="screenshot" src="https://user-images.githubusercontent.com/1844746/130278872-4e58557b-965e-4f79-8e43-8670a601f8c6.png" width="390" />
—and just removed the long list of social media links entirely:
> <img alt="screenshot" src="https://user-images.githubusercontent.com/1844746/130278881-df9315c6-4a59-4d28-8b63-76533de264af.png" width="504" />
I’m not very confident about that decision; maybe it should still have Mastodon?
=> Re: Making the announce mailing list more prominent

_posts/2021-08-18-Lightning-Talks.md
This change adds a new blog post announcing our Lightning Talks. The post content was prepared by @sramkrishna and @alisonjudy
=> Add Lightning Talks Blog Post

_posts/2021-11-03-seagl-stickers.md
As we need a smaller url of the sticker pack blog post for the interstitials, I added the `/stickers`
=> Added a redirect url for the sticker pack blog post

_posts/2021-10-28-seagl-2021-social.md
- /social_events now redirects to the blog post, for use in the interstitials (temporary, just for conference use)
- Added links to the social room and DevOps Party Games Twitch
=> Update social events blog post

style_guide.md
The results of the color poll assigned the excellent name *Bread For Screaming At* to pure white `#FFFFFF`. At @altsalt’s suggestion I’d like to propose reassigning that name to the off-white `#FFFCF7` instead, and using the second place name for `#FFFFFF`. The resulting palette would be:
- `#1D7193` Tidal Blue
- `#0C5A73` Puget Sound
- `#074558` Deep Ocean
- `#FCB320` French Fry Gold
- `#B1742A` Wet Sand
- `#FFFFFF` Feather White
- `#E0E0E0` Brave Gull
- `#CCCCCC` Gloomy Sky
- `#B3B3B3` Stormy Sky
- `#565656` Storm Cloud
- `#0D0D0D` Penguin Black
- `#FFFCF7` Bread For Screaming At
Rationale:
- `#FFFFFF` already has a commonly used name, *white*, so it’s confusing to dramatically rename it.
- `#FFFCF7` is a more accurate bread color.
- The submitter of the name *Bread For Screaming At* …
=> Use “Bread For Screaming At” for off-white, not pure white

_posts/2022-07-06-CFP-Live.md
This change updates the 2022 CFP Post so that the talk topics match OSEM.
=> Update 2022 CFP Talk Topics to match OSEM

_posts/2022-07-06-CFP-Live.md, _posts/2022-08-04-CFP-Extended.md
This change adds a new blog post announcing the extension of our CFP. I
am also updating the original CFP post to note this extension in order
to avoid confusion.
=> Announce CFP Extension

_data/sponsors.yml
The site is currently failing to build due to the following error:
```
github-pages 227 | Error:  (/github/workspace/_data/sponsors.yml): found a tab character where an indentation space is expected while scanning a block scalar at line 115 column 16
```
This change fixes the whitespace.
=> Fix sponsosrs.yml Whitespace

_posts/2022-11-04-day-1-schedule.md
This change adds a new blog post sharing the schedule for day 1 of SeaGL 2022
=> Publish 2022 Day 1 Schedule Blog Post

_posts/2022-11-05-day-2-schedule.md
This change adds a new blog post publishing the 2022 Day 2 Schedule
=> Publish 2022 Day 2 Schedule

_config.yml
To verify our Mastodon account `@seagl@mastodon.social` we must include `rel=me` on the link
From mastodon profile:
`You can verify yourself as the owner of the links in your profile metadata. For that, the linked website must contain a link back to your Mastodon profile. After adding the link you may need to come back here and re-save your profile for the verification to take effect. The link back must have a rel="me" attribute. `
=> Update Mastodon link for verification purposes

_data/sponsorship.yml
Added to 2023:
DevITJobs.us
PLUG
RaiseME
FOSSlife
Tux Digital
Changed URL:  DevOpsDays.  From 2022 to 2024.
=> Updated sponsorship.yml

_posts/2021-11-03-seagl-stickers.md
As we have new stickers, I updated the sticker packs, but signal requires the creation of a new pack (and with that we have a new link)
=> Updated Signal sticker link in blog post

meet.md
=> Remove IRC from community chat instructions

css/app/seagl.scss
@theKimSingh Thanks for catching this. Look okay?
> ![886e23b 480px](https://github.com/user-attachments/assets/5a7df916-9820-4994-aa65-395cc29f3557)
480px:
> ![6661e70 vs 886e23b at 480px](https://github.com/user-attachments/assets/ba495b9e-2d0a-4763-8d3c-5c60c6603a62)
910px:
> ![6661e70 vs 886e23b at 910px](https://github.com/user-attachments/assets/7f7aee3f-d28c-47da-a5d5-948e65a5644f)
1200px:
> ![6661e70 vs 886e23b at 1200px](https://github.com/user-attachments/assets/7c41c930-c34d-4fdc-b21b-962644bd5d13)
=> Correct aspect ratio of logo on narrow viewports
